---
Name: discussionsconfig
---
Users:
  verification_groups:
    - discussions-posters
CommentingController:
  extensions:
    - DiscussionCommentControllerExtension
Member:
  extensions:
    - DiscussionsMember
Group:
  extensions:
    - DiscussionsGroup
Comment:
  extensions:
    - DiscussionsComment
Users_Account_Controller:
  extensions:
    - DiscussionsUsersController
