---
Name: discussionsconfig
---
Users:
  verification_groups:
    - discussions-posters

Discussion:
  extensions:
    - CommentsExtension
  comments:
    require_login: true
    required_permission: "DISCUSSIONS_POSTING"
    order_comments_by: '"Created" ASC'

CommentingController:
  extensions:
    - DiscussionCommentControllerExtension
Member:
  extensions:
    - DiscussionsMember
Group:
  extensions:
    - DiscussionsGroup
Comment:
  extensions:
    - DiscussionsComment
Users_Account_Controller:
  extensions:
    - DiscussionsUsersController
